### ISSUE TITLE
Cannot post a new content

### ISSUE THREAD

**Issue by squest** [arie741/zenblogv2#3]
The ring anti-forgery cause a problem, check how you can use token to enable the posting form.

**Comment by arie741** [comment]
i dont understand this issue at all

**Comment by squest** [comment]
From the post-blog section, I can't post a new post to the blog

**Comment by arie741** [comment]
@squest i dont have any ideas myself

**Comment by arie741** [comment]
@squest help me im stuck here

**Comment by arie741** [comment]
@squest FINALLY SOLVED IT

**Comment by mavbozo** [comment]
I clone your repo and run the server. But I still can not post a new content.

**Comment by arie741** [comment]
@mavbozo @squest i think this will solve it c91888a4c621cf79858bf64fb20aa84d093aa2c8 pls check

**Comment by arie741** [comment]
@mavbozo @squest is it working guys?

**Comment by mavbozo** [comment]
works for me
