### ISSUE TITLE
Text editor for clojure

### ISSUE THREAD

**Issue by arie741** [arie741/zenblogv2#7]
@squest any suggestion on what's the best text editor(text area) for clojure?

**Comment by squest** [comment]
You mean to be used as web based text-editing? or a text-editing for development? for development my choice obviously intellij or emacs

**Comment by arie741** [comment]
@squest i mean for web based text-editing

**Comment by squest** [comment]
No Idea, so far I only use github for editing online... What do you need this for?

**Comment by squest** [comment]
You can steal the code from 4clojure editor, it's open source, so they must have the code for the editor somewhere in their github.
